<?php 

namespace App\ACF_Fields;

use App\ACF_Fields\AbstractFieldRegistration;

class SiteSettings extends AbstractFieldRegistration
{
    /**
     * Register ACF fields for this group
     */
    public function register()
    {
        acf_add_local_field_group(array(
            'key' => 'group_5dcbdab2874f3',
            'title' => 'Site Settings',
            'fields' => array(
                array(
                    'key' => 'field_5dcbdabd8390f',
                    'label' => 'General',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'left',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_5dcbdaca83910',
                    'label' => 'Site Logo',
                    'name' => 'site_logo',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_5dcbe728f41ff',
                    'label' => '404 Error Page',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'left',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_5dcbe732f4200',
                    'label' => '404 Error Page Text',
                    'name' => '404_error_page_text',
                    'type' => 'wysiwyg',
                    'instructions' => 'Add content to assist users who reach a non-existent page.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                ),
                array(
                    'key' => 'field_5dcbe776729b0',
                    'label' => 'Social Networks',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'left',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_5dcbe786729b1',
                    'label' => 'Twitter',
                    'name' => 'twitter_link',
                    'type' => 'url',
                    'instructions' => 'Add your Twitter link',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_5dcbe799729b2',
                    'label' => 'LinkedIn',
                    'name' => 'linkedin_link',
                    'type' => 'url',
                    'instructions' => 'Add your LinkedIn link',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_5dcbe7b8729b3',
                    'label' => 'Facebook',
                    'name' => 'facebook_link',
                    'type' => 'url',
                    'instructions' => 'Add your Facebook Link',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_5dcbe7c6729b4',
                    'label' => 'YouTube',
                    'name' => 'youtube_link',
                    'type' => 'url',
                    'instructions' => 'Add your YouTube link',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_5dcbe7d6729b5',
                    'label' => 'Instagram',
                    'name' => 'instagram_link',
                    'type' => 'url',
                    'instructions' => 'Add your Instagram link',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'acf-options-site-settings',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'modified' => 1573644278,
        ));
    }
}
